name: Update API Files

on:
  pull_request:
    types: 
      - closed

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: Install dependencies
      run: npm install axios
    - name: Update API Files
      run: node apiUpdateFiles.js